project:
  type: website

website:
  title: "blog.jamesmcguigan.com"
  navbar:
    right:
      - index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/jamesmcguigan/
      - icon: github
        href: https://github.com/JamesMcGuigan
      - icon: kaggle
        href: https://www.kaggle.com/jamesmcguigan
      - icon: twitter
        href: https://www.linkedin.com/in/jamesmcguigan/

    left:
      - href: blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css



