# Example: https://github.com/fastai/nbdev/blob/master/nbs/_quarto.yml
# Example: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml

project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  # title: "blog.jamesmcguigan.com"
  open-graph: true
  twitter-card:
    creator: "@JamesMcGuigan42"
  google-analytics: "UA-27712984-4"

  # https://quarto.org/docs/websites/website-navigation.html#github-links
  repo-url:     https://github.com/JamesMcGuigan/blog
  repo-branch:  master
  repo-actions: [edit]  # [issue, edit]

  # DOCS: https://quarto.org/docs/websites/website-search.html
  search:
    location: navbar    # navbar, sidebar
    type:     textbox   # overlay, textbox
    copy-button: false

  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/JamesMcGuigan42
      - icon: linkedin
        href: https://www.linkedin.com/in/jamesmcguigan/
      - icon: github
        href: https://github.com/JamesMcGuigan
      - icon: kaggle
        href: https://www.kaggle.com/jamesmcguigan
      - icon: stackoverflow
        href: https://stackoverflow.com/users/748503/james-mcguigan

    left:
      - text: James McGuigan
        href: index.qmd
      - text: Websites
        href: content/websites/index.qmd
      - text: Essays
        href: content/essays/index.qmd
      - text: Projects
        href: content/projects/index.qmd

  # DOCS: https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
  sidebar:
    - title: Default  # hide sidebar on untitled pages
      style: docked   # floating
      alignment: center
      search: true
      border: true
      collapse-level: 2


    - title: Essays   # match | left.text: Essays
      contents:
        - "content/essays/index.qmd"
        - auto: "content/essays/**/*.qmd"

    - title: Projects  # match | left.text: Notes
      contents:
        - "content/projects/index.qmd"
        - auto: "content/projects/**/*.qmd"

format:
  html:
    page-layout: article
    theme:
      light: pulse   # quartz # flatly # vapor
      # dark:  darkly  # darkly
    toc: true
    toc-depth: 5
    css: assets/styles.css
    include-in-header:
      - assets/MemberSpace.html
      # - assets/MemberStack.html  # UNUSED: requires ES6 import