# Example: https://github.com/fastai/nbdev/blob/master/nbs/_quarto.yml
# Example: https://github.com/quarto-dev/quarto-web/blob/main/_quarto.yml

project:
  type: website
  preview:
    port: 3000
    browser: true

website:
  # title: "blog.jamesmcguigan.com"
  open-graph: true
  twitter-card:
    creator: "@JamesMcGuigan42"
  google-analytics: "UA-27712984-4"

  # https://quarto.org/docs/websites/website-navigation.html#github-links
  repo-url:     https://github.com/JamesMcGuigan/blog
  repo-branch:  master
  repo-actions: [edit]  # [issue, edit]

  # DOCS: https://quarto.org/docs/websites/website-search.html
  search:
    location: navbar    # navbar, sidebar
    type:     textbox   # overlay, textbox
    copy-button: false

  navbar:
    right:
      - href: index.qmd
      - icon: twitter
        href: https://www.linkedin.com/in/jamesmcguigan/
      - icon: linkedin
        href: https://www.linkedin.com/in/jamesmcguigan/
      - icon: github
        href: https://github.com/JamesMcGuigan
      - icon: kaggle
        href: https://www.kaggle.com/jamesmcguigan

    left:
      - text: Blog
        href: blog/index.qmd
      - text: Documentation
        href: docs/index.qmd

  # DOCS: https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
  sidebar:
    - title: Default  # hide sidebar on untitled pages
      style: docked   # floating
      alignment: center
      search: true
      border: true
      collapse-level: 5


    - title: Blog           # match | left.text: Blog
      contents:
        - "blog/index.qmd"
        - auto: "blog/**/*.qmd"

    - title: Documentation  # match | text: Documentation
      contents:
        - "docs/index.qmd"
        - auto: "docs/**/*.qmd"

format:
  html:
    page-layout: article
    theme:
      light: pulse   # quartz # flatly # vapor
      dark:  darkly  # darkly
    toc: true
    toc-depth: 5
    css: assets/styles.css
    include-in-header:
      - assets/MemberSpace.html
      # - assets/MemberStack.html  # UNUSED: requires ES6 import



