---
title: Keto Carnivore Weightlifting
author: James McGuigan
categories: [keto,fitness]
---

4.5 months ago, I bought myself a 30kg (2x15kg) set of weightlifting dumbbells. One of the personal trainers on my Facebook/Instagram video feed showed me a really simple full-body compound exercise: floor to ceiling. It’s simplicity gets your legs, arms, back, and shoulders.

Facebook/Instagram also showed me (hit the like button for more) a range of other motions to train specific muscle groups.

When I first started, I could barely do 5 reps of floor to ceiling before breaking out into a sweat, with a racing heart. It's a great exercise for overloading and ripping the muscles.

Based on the principles of HIIT training, I would push my muscles to their limit, give myself a minute or so for my heart to stop racing, and then try again. I would usually aim for 3 sets. After a few months, I started to grow stronger. I could do sets of 10-8-6 reps, and eventually, 3 sets of 10 reps didn’t seem that hard anymore. HIIT also triggers the afterburn effect, raising your daily metabolism even after you're done exercising.

This is an ultra-efficient exercise, taking only 5-15 minutes. I tried to make it a daily habit, occasionally giving my muscles a few days to rest, but trying to keep them in a state where you constantly feel the glow. Leave the weights visible where you frequently walk past them, and do this exercise before getting into the shower. It requires less effort than getting dressed for the gym.

Other side effects include making it easier to go on multi-day walkabouts while carrying an 11.1kg backpack across multiple cities.

I did encounter a PureGym with a day pass on my travels. The difference is they had the full range of equipment to train every muscle at every angle with a range of smaller weights. I just kept bouncing between machines and doing one set at each. As a fun day out, it seemed useful for targeting the skeletal muscles and the slow twitch muscle fibers. Still, it’s hard to beat the simplicity of a pair of heavy dumbbells.

I’ve decided it’s time to level up to the next weight class. I have rearranged the weights, so I now have one 23kg dumbbell and a smaller 8kg dumbbell. I can only train one arm at a time, but Amazon is sending me a matching set in the post.

That 23kg dumbbell puts me back to where I started. I can barely do 5 reps of floor to ceiling with it, and I can feel the burn in my muscles again. The 8kg dumbbell is also interesting as it allows a wider range of side exercises that become impossible with an oversized weight. Maybe in another 6 months, these bigger weights will seem easy again.

I’ve combined this exercise routine with a keto carnivore diet (zero/low carbs + high protein + salt), as well as intermittent fasting and sometimes one meal a day or occasional 36h fasts (go two sleeps without eating). I've already lost at least a stone (6kg) and possibly a second since the beginning of the year. I only recently bought a scale and keep track of my weight using the Apple Health app.

My BMI is back down to overweight, my waistline seems a little less excessive, and some of that fat has turned into muscle. I haven’t reached the stage of being jacked, but there is some muscle definition visible.

Anyways, this is what's possible without leaving the house or paying for a gym membership.