# Source: https://raw.githubusercontent.com/beatrizmilz/blog-en/main/.github/workflows/build-blog.yaml

on:
  workflow_dispatch:
  push:
    branches: master

name: Render and Publish


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run:  pwd; ls -la


      ### Python
      
      # Source: https://github.com/actions/starter-workflows/blob/82c43562976aef3d8f02643e00e979d65993244c/ci/python-app.yml
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # - name: Test with pytest
      #   run: |
      #     pytest


      # ### R dependencies

      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     use-public-rspm: true

      # - uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |
      #       any::rmarkdown
      #       any::tidyverse
      #       any::xml2
      #       any::downlit
      #       any::here


      # ### Quarto 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
         tinytex: true
      - run: quarto --version
      - run: quarto check

      # # Source: https://github.com/quarto-dev/quarto-actions/tree/main/render
      # - name: Render Quarto Project
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     to: html # If set, it will be equivalent to `quarto render --to html`
      #     # path: . # By default, the current working dir is used i.e `quarto render .`

      # - name: Publish to GitHub Pages (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: gh-pages
      #     path: "_site/"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions


      - name: Build Quarto Project
        run: |
          quarto render .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "james.mcguigan@gmail.com"
          git config --global user.name  "James McGuigan"
          
          quarto publish gh-pages --no-prompt
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
